Added two new cars
mugshepherd/lets-practice-gitFlow pull request #15
Opened 2018-09-19 14:43 UTC by bayramcura

## CHANGES

- Added car_bc_1.md and car_bc_2.md

2018-09-19 15:02 UTC, pete85 requested changes
Change colour of car 2 to black metallic

2018-09-19 15:07 UTC, pete85 reviewed
Please change the colour of car 1

2018-09-19 15:13 UTC, pete85 approved these changes

2018-09-20 09:42 UTC, mugshepherd approved these changes
looks good.  thanks for the updates.

2018-10-08 14:08 UTC, closed without merging